
import { State, User, Booking as BookingType, Feedback as FeedbackType, Inquiry } from './frontend/src/types';

declare global {
  type DesignModel = any;
  type Category = any;
  type Package = any;
  type RoomType = any;
  type StyleType = any;
  var RoomType: any;
  var StyleType: any;
  var User: any;
  var Inquiry: any;
  type User = any;
  type Inquiry = any;
  var getSmartDesignSuggestions: any;
  var state: State;
  var apiFetch: (path: string, options?: RequestInit, timeoutMs?: number) => Promise<Response>;
  var getAuthHeaders: () => Record<string, string>;
  var normalizeBookingRecord: (booking: any) => BookingType;
  var getBookings: () => any[];
  var getBookingSortScore: (booking: any) => number;
  var ensureAdminToken: () => Promise<void>;
  var shouldRenderRefreshResult: (options: any) => boolean;
  var renderStabilized: () => void;
  var initAdminChartsWhenVisible: () => void;
  var scheduleAdminChartsRetry: () => void;
  var mergeServerLikesWithLocalDislikes: (likes: any[]) => any[];
  var updateAdminCharts: () => void;
  var logPerf: (label: string, start: number) => void;
  var getPerfNow: () => number;
  var CHATBOT_HISTORY_MAX: number;
  var chatbotHistoryState: any[];
  var persistChatbotHistory: () => void;
  var adminRefreshInFlight: boolean;
  var render: () => void;
  var navigateTo: (tab: string, ...args: any[]) => void;
  var updateBooking: (id: string, patch: any) => void;
  var updatePayment: (id: string, patch: any) => void;
  var syncDashboardsAndInvoices: (options?: { silent?: boolean }) => Promise<void>;
  var refreshCustomerData: (options?: { silent?: boolean }) => Promise<void>;
  var getBotResponse: (query: string) => any;
  var getChatbotUserType: () => string;
  var chatbotStatsState: any;
  var updateGuestChatbotProfileAfterMessage: (...args: any[]) => void;
  var persistChatbotStats: () => void;
  var filterBookingsForCurrentUser: (bookings: any[]) => any[];
  var handlePaymentRedirect: (transactionId: string) => void;
  var escapeHtml: (str: string) => string;
  var formatMonthYearDate: (date: any) => string;
  var runWhenBrowserIdle: (task: () => void, timeout?: number) => void;
  var getCustomerVisibleCategories: (...args: any[]) => any[];
  var getCustomerDesignPool: () => any[];
  var normalizeCategoryKey: (key: string) => string;
  var designMatchesCategory: (design: any, categoryKeys: Set<string>) => boolean;
  var getCategoryKeySet: (filter: string, categories: any[]) => Set<string>;
  var resolveDesignDisplayName: (design: any, options?: any) => string;
  var getDesignAmount: (design: any) => number;
  var getDesignForImage: (...args: any[]) => any;
  var getPackageBackgroundImage: (pkg: any) => string;
  var getPackageDisplayImage: (pkg: any) => string;
  var getInitials: (name: string) => string;
  var renderVideoEmbedOrTag: (...args: any[]) => string;
  var getCategories: () => any[];
  var getDesigns: () => any[];
  var renderImageThumb: (url: string, title?: string, sizeClass?: string, textClass?: string, isMotion3d?: boolean) => string;
  var renderEmojiOptions: (fieldName: string) => string;
  var formatCurrency: (amount: number) => string;
  var renderCategoryThumb: (cat: any, sizeClass?: string, textClass?: string) => string;
  var renderModelViewer: (design: any) => string;
  var getLuxuryShowroomStore: () => any;
  var getShowroomDisplayImages: (...args: any[]) => any[];
  var getPackages: (...args: any[]) => any;
  var normalizeCategoryMotion3D: (cat: any) => any;
  var getTextColorForBackground: (bg: string) => string;
  var getCustomerDisplayPackages: () => any[];
  var getActiveAnnouncements: () => any[];
  var getAnnouncementEmoji: (announcement: any) => string;
  var getGalleryDesignCandidates: (...args: any[]) => any[];
  var getFilenameKey: (filename: string) => string;
  var getCategoryMatchKeySet: (...args: any[]) => Set<string>;

  // --- Additional globals referenced by backend/src/modules ---
  var normalizeAssetUrl: (url: string) => string;
  var normalizeKey: (key: string) => string;
  var sanitizeDisplayName: (name: string) => string;
  var normalizeDesignMotion3D: (design: any) => any;
  var mergeDesignsPreferServer: (local: any[], server: any[] | null) => any[];
  var parseAmountValue: (value: any) => number;
  var normalizeCalcCategoryKey: (key: string) => string;
  var getAdminImageLibrary: () => any[];
  var getCanonicalCategoryImages: (...args: any[]) => any[];
  var featureImageMap: Record<string, string>;
  var getPackagesSync: () => any[];
  var getPayments: () => any[];
  var getStoredPaidDesigns: (...args: any[]) => any[];
  var setStoredPaidDesigns: (...args: any[]) => void;
  var getBookingPaymentStatus: (booking: any) => string;
  var getBookingAmount: (booking: any) => number;
  var resolveBookingDesignContext: (booking: any) => any;
  var getEffectiveBookings: () => any[];
  var renderCategoryGallery: (...args: any[]) => string;
  var renderGallery: (...args: any[]) => string;
  var renderNavItems: () => any[];
  var getHomeCategoryImages: (categories: any[]) => any[];
  var buildSpideyHeroSlides: () => any[];
  var getRoomRelatedImages: (...args: any[]) => any[];
  var renderAiStudio: (...args: any[]) => string;
  var writeStorage: (key: string, value: any) => void;
  var STORAGE_KEYS: Record<string, string>;
  var COMPANY_INFO: Record<string, any>;
  var INITIAL_SERVICE_SHOWCASES: any[];
  var INTERIOR_DESIGN_VIDEOS: any[];
  var PORTFOLIO_CATEGORY_NAME_MAP: Record<string, string>;
  var chatbotSettingsState: any;
  var detectCustomerInterest: (query: string) => any;
  var getDesignSuggestionsByInterest: (...args: any[]) => any[];
  var bookingIntentPattern: RegExp;
  var suggestionIntentPattern: RegExp;
  var ensurePortfolioFeedbackSeeded: () => void;
  var generateQuarterlyMetricsFromBookings: (bookings: any[]) => any;
  var getPortfolioDisplayBookings: (...args: any[]) => any[];
  var getPortfolioSampleCategorySeries: () => any[];
  var getQuarterlySampleMetrics: () => any;
  var resolvePortfolioCategoryId: (...args: any[]) => string;
  var resolvePortfolioCategoryName: (...args: any[]) => string;
  var resolvePortfolioDesignName: (...args: any[]) => string;
  var getCustomerVisibleDesigns: (...args: any[]) => any[];
  var persistState: () => void;
  var getCustomerCategoryBackedDesigns: () => any[];
  var getDislikeFeedbackRecords: () => any[];
  var getCustomerDesignPresentation: (design: any) => { displayName: string; imageUrl: string; categoryId: string; categoryName: string; };
  var renderCardPaymentModal: () => string;
  var renderPaymentSuccessModal: () => string;
  var ensureDislikeFeedbackSampleData: () => void;
  var fetchPhonePeStatus: (merchantTransactionId: string, token?: string) => Promise<any>;
  var isBookingApprovedForPayment: (booking: any) => boolean;
  var renderAdminCustomerDetailsModal: () => string;
  var renderAdminDesignEditor: any;
  var renderCatalogPreviewModal: any;
  var getAdminChartTheme: any;
  var refreshAdminData: any;
  var mergeUserProfileFields: any;
  var syncCustomerPackagePreferences: any;
  var upsertUserInState: any;
  var refreshPublicFeedbacks: any;
  var getSelectedModel: any;
  var perfNow: any;
  var calculatePrice: any;
  var resolvePlayableVideoUrl: any;
  var toYouTubeEmbedUrl: any;
  var normalizeShowcaseRecord: any;
  var applyCategoryBackground: any;
  var mergeExistingLocalFeedbackVideos: any;
  var calculatePortfolioMetricsFromBookings: any;
  var SERVICE_MANAGER_SAMPLES: any;
  var normalizeShowroomRecord: any;
  var parseRelatedImageUrlsInput: any;
  var getShowcaseRelatedImagesFromFormState: any;
  var toggleCustomerPackagePreference: any;
  var openPackageCardPayment: any;
  var applyDiscountCodeToBooking: any;
  var normalizePromoCode: any;
  var buildPackageRoomsFromCategory: any;
  var focusCatalogPreviewDialog: any;
  var closeCatalogPreview: any;
  var isBookingActionPending: any;
  var setBookingActionPending: any;
  var patchBookingStatusInState: any;
  var addDislikeFeedbackRecord: any;
  var removeCustomerPackagePreference: any;
  var removeCustomerPreference: any;
  var setHiddenBookingIds: any;
  var openCustomerBookingDetails: any;
  var loadPackageIntoAdminForm: any;
  var PACKAGE_PREFERENCES_KEY: any;
  var PACKAGE_CACHE_RESET_VERSION_KEY: any;
  var purgeLegacyPackageCaches: any;
  var updateDislikeFeedbackReply: any;
  var setDislikeFeedbackRecords: any;
  var ensureDesignsForAllCategories: any;
  var logPerfMetric: any;
  var updatePortfolioContentField: any;
  var getActiveTabFromPath: any;
  var restoreScrollPosition: any;
  var loadState: any;
  var memoizeAdminSection: any;
  var getCollectionStamp: any;
  var renderAdminDislikeFeedbackSection: any;
  var renderUploadModal: any;
  var renderCatalogActionDialog: any;
  var getCategoryStrictKeySet: any;
  var getRollingMonthSeries: any;
  var normalizeHistoricalDate: any;
  var getAdminCategoryChartPayload: any;
  var getCategoryChartColors: any;
  var adminChartsAutoRefreshId: any;
  var adminChartsVisibilityBound: any;
  var adminChartsRefreshInFlight: any;
  var isAdminInteractionWarm: any;
  var hasPendingBookingActions: any;
  var getAdminRefreshRenderSignature: any;
  var adminLastRefreshRenderSignature: any;
  var ADMIN_CHARTS_AUTO_REFRESH_MS: any;
  var loadAdminChartConstructor: any;
  var adminChartsInitInFlight: any;
  var updateDesign: any;
  var saveDesign: any;
  var deleteDesign: any;
  var dashboardSyncInFlight: any;
  var autoSyncPortfolioMetrics: any;
  var postLoginSyncTimer: any;
  var createBooking: any;
  var createPayment: any;
  var triggerBookingDataSync: any;
  var createPhonePePayment: any;
  var addFeedback: any;
  var updateCategory: any;
  var saveCategory: any;
  var AIDesignVariant: any;
  var applyDesignVisualization: any;
  var designElements: any;
  var resetChatbotMessages: any;
  var createMessage: any;
  var getQuickAction: any;
  var getEnhancedChatbotResponse: any;
  var trackChatbotMessageStats: any;
  var recordChatbotHistory: any;
  var handleChatNavigationIntent: any;
  var init: any;
  var renderMarkdownText: any;
  var handleSendChat: any;
  var fetchWithTimeout: any;
  var DEFAULT_PORTFOLIO_CONTENT: any;
  var root: any;
  var pathToTab: any;
  var tabToPath: any;
  var setThemeVars: any;
  var stopAdminChartsAutoRefresh: any;
  var adminChartsRetryTimer: any;
  var adminChartsObserver: any;
  var charts: any;
  var RefreshOptions: any;
  var customerRefreshInFlight: any;
  var DEFAULT_CALC_LIBRARY_REQUIREMENTS: any;
  var CATEGORY_QUALITY_CONCEPTS: any;
  var ensureModelViewerLoaded: any;
  var bindModelViewers: any;
  var init3DViewers: any;
  var startAdminChartsAutoRefresh: any;
  var initPortfolioCharts: any;
  var cleanupPortfolioCharts: any;
  var renderLogin: any;
  var renderAccessDenied: any;
  var ChatbotUserType: any;
  var getAdminChartMetrics: any;
  var normalizeBookingPaymentStatus: any;
  var formatPaymentMethodLabel: any;
  var formatInvoiceDateTime: any;
  var getPaidPortfolioBookings: any;
  var getCategoryForPackage: any;
  var getHiddenBookingIds: any;
  var organizeBookingsByStatus: any;
  var syncPaidDesignsFromBookings: any;
  var getEligibleBookingsForDiscount: any;
  var getSavedPackageIdsForUser: any;
  var isQATestDesign: any;
  var ensureDesignsForCategory: any;
  var getAnnouncementMatchedDiscountCodes: any;
  var getEligibleBookingForDiscountCode: any;
  var getBookingDisplayLabel: any;
  var renderAdminDashboardSection: any;
  var renderAdminBookingsSection: any;
  var renderAdminInvoicesSection: any;
  var renderAdminInquiriesSection: any;
  var renderAdminCategoriesSection: any;
  var renderAdminDesignManagerSection: any;
  var renderAdminCatalogSection: any;
  var renderAdminPackageManagerSection: any;
  var renderAdminCalculatorSection: any;
  var renderAdminFeedbackSection: any;
  var renderAdminChatbotManagerSection: any;
  var renderAdminAnnouncementsSection: any;
  var renderAdminThemeSection: any;
  var renderAdminDesignStudioSection: any;
  var renderAdminServicesSection: any;
  var renderAdminPortfolioSection: any;
  var renderAdminLuxuryEditorSection: any;
  var renderAdminShowroomsSection: any;
  var renderAdminShowcaseSection: any;
  var renderAdminCustomersSection: any;
  var normalizeTemplateMarkup: any;
  var renderAdminBookingDetailsModal: any;
  var renderAdminInquiryDetailsModal: any;
  var renderBookingDetailsModal: any;
  type AIDesignVariant = any;

  // Global type aliases for use in extracted modules
  type Booking = BookingType;
  type Feedback = FeedbackType;
}

export {};
