
import { State, User, Booking as BookingType, Feedback as FeedbackType, Inquiry } from './frontend/src/types';

declare global {
  type DesignModel = any;
  type Category = any;
  type Package = any;
  type RoomType = any;
  type StyleType = any;
  var state: State;
  var apiFetch: (path: string, options?: RequestInit, timeoutMs?: number) => Promise<Response>;
  var getAuthHeaders: () => Record<string, string>;
  var normalizeBookingRecord: (booking: any) => BookingType;
  var getBookings: () => any[];
  var getBookingSortScore: (booking: any) => number;
  var ensureAdminToken: () => Promise<void>;
  var shouldRenderRefreshResult: (options: any) => boolean;
  var renderStabilized: () => void;
  var initAdminChartsWhenVisible: () => void;
  var scheduleAdminChartsRetry: () => void;
  var mergeServerLikesWithLocalDislikes: (likes: any[]) => any[];
  var updateAdminCharts: () => void;
  var logPerf: (label: string, start: number) => void;
  var getPerfNow: () => number;
  var CHATBOT_HISTORY_MAX: number;
  var chatbotHistoryState: any[];
  var persistChatbotHistory: () => void;
  var adminRefreshInFlight: boolean;
  var render: () => void;
  var navigateTo: (tab: string, ...args: any[]) => void;
  var updateBooking: (id: string, patch: any) => void;
  var updatePayment: (id: string, patch: any) => void;
  var syncDashboardsAndInvoices: (options?: { silent?: boolean }) => Promise<void>;
  var refreshCustomerData: (options?: { silent?: boolean }) => Promise<void>;
  var getBotResponse: (query: string) => any;
  var getChatbotUserType: () => string;
  var chatbotStatsState: any;
  var updateGuestChatbotProfileAfterMessage: (...args: any[]) => void;
  var persistChatbotStats: () => void;
  var filterBookingsForCurrentUser: (bookings: any[]) => any[];
  var handlePaymentRedirect: (transactionId: string) => void;
  var escapeHtml: (str: string) => string;
  var formatMonthYearDate: (date: any) => string;
  var runWhenBrowserIdle: (task: () => void, timeout?: number) => void;
  var getCustomerVisibleCategories: (...args: any[]) => any[];
  var getCustomerDesignPool: () => any[];
  var normalizeCategoryKey: (key: string) => string;
  var designMatchesCategory: (design: any, categoryKeys: Set<string>) => boolean;
  var getCategoryKeySet: (filter: string, categories: any[]) => Set<string>;
  var resolveDesignDisplayName: (design: any, options?: any) => string;
  var getDesignAmount: (design: any) => number;
  var getDesignForImage: (...args: any[]) => any;
  var getPackageBackgroundImage: (pkg: any) => string;
  var getPackageDisplayImage: (pkg: any) => string;
  var getInitials: (name: string) => string;
  var renderVideoEmbedOrTag: (...args: any[]) => string;
  var getCategories: () => any[];
  var getDesigns: () => any[];
  var renderImageThumb: (url: string, title?: string, sizeClass?: string, textClass?: string, isMotion3d?: boolean) => string;
  var renderEmojiOptions: (fieldName: string) => string;
  var formatCurrency: (amount: number) => string;
  var renderCategoryThumb: (cat: any, sizeClass?: string, textClass?: string) => string;
  var renderModelViewer: (design: any) => string;
  var getLuxuryShowroomStore: () => any;
  var getShowroomDisplayImages: (...args: any[]) => any[];
  var getPackages: (...args: any[]) => any;
  var normalizeCategoryMotion3D: (cat: any) => any;
  var getTextColorForBackground: (bg: string) => string;
  var getCustomerDisplayPackages: () => any[];
  var getActiveAnnouncements: () => any[];
  var getAnnouncementEmoji: (announcement: any) => string;
  var getGalleryDesignCandidates: (...args: any[]) => any[];
  var getFilenameKey: (filename: string) => string;
  var getCategoryMatchKeySet: (...args: any[]) => Set<string>;

  // --- Additional globals referenced by backend/src/modules ---
  var normalizeAssetUrl: (url: string) => string;
  var normalizeKey: (key: string) => string;
  var sanitizeDisplayName: (name: string) => string;
  var normalizeDesignMotion3D: (design: any) => any;
  var mergeDesignsPreferServer: (local: any[], server: any[] | null) => any[];
  var parseAmountValue: (value: any) => number;
  var normalizeCalcCategoryKey: (key: string) => string;
  var getAdminImageLibrary: () => any[];
  var getCanonicalCategoryImages: (...args: any[]) => any[];
  var featureImageMap: Record<string, string>;
  var getPackagesSync: () => any[];
  var getPayments: () => any[];
  var getStoredPaidDesigns: (...args: any[]) => any[];
  var setStoredPaidDesigns: (...args: any[]) => void;
  var getBookingPaymentStatus: (booking: any) => string;
  var getBookingAmount: (booking: any) => number;
  var resolveBookingDesignContext: (booking: any) => any;
  var getEffectiveBookings: () => any[];
  var renderCategoryGallery: (...args: any[]) => string;
  var renderGallery: (...args: any[]) => string;
  var renderNavItems: () => any[];
  var getHomeCategoryImages: (categories: any[]) => any[];
  var buildSpideyHeroSlides: () => any[];
  var getRoomRelatedImages: (...args: any[]) => any[];
  var renderAiStudio: (...args: any[]) => string;
  var writeStorage: (key: string, value: any) => void;
  var STORAGE_KEYS: Record<string, string>;
  var COMPANY_INFO: Record<string, any>;
  var INITIAL_SERVICE_SHOWCASES: any[];
  var INTERIOR_DESIGN_VIDEOS: any[];
  var PORTFOLIO_CATEGORY_NAME_MAP: Record<string, string>;
  var chatbotSettingsState: any;
  var detectCustomerInterest: (query: string) => any;
  var getDesignSuggestionsByInterest: (...args: any[]) => any[];
  var bookingIntentPattern: RegExp;
  var suggestionIntentPattern: RegExp;
  var ensurePortfolioFeedbackSeeded: () => void;
  var generateQuarterlyMetricsFromBookings: (bookings: any[]) => any;
  var getPortfolioDisplayBookings: (...args: any[]) => any[];
  var getPortfolioSampleCategorySeries: () => any[];
  var getQuarterlySampleMetrics: () => any;
  var resolvePortfolioCategoryId: (...args: any[]) => string;
  var resolvePortfolioCategoryName: (...args: any[]) => string;
  var resolvePortfolioDesignName: (...args: any[]) => string;
  var getCustomerVisibleDesigns: (...args: any[]) => any[];
  var persistState: () => void;

  // Global type aliases for use in extracted modules
  type Booking = BookingType;
  type Feedback = FeedbackType;
}

export {};
